gem 'decent_exposure'
gem 'haml'
gem 'pg'
gem 'pry'

gem_group :test, :development do
  gem 'factory_girl'
  gem 'fivemat'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rspec'
end

gem_group :assets do
  gem "twitter-bootstrap-rails"
end

gem_group :test do
  gem 'shoulda-matchers'
end

ruby_version = `rvm current`.sub("\n",'')
run "rvm gemset create #{app_name}"
gemset = "#{ruby_version}@#{app_name}"

class_eval do
  define_method(:with_rvm) { |cmd| run "rvm #{gemset} do #{cmd}" }
end

def new_file(name, content)
  create_file name, content, :verbose => false
end

with_rvm 'gem install bundler'
with_rvm 'bundle install'
new_file ".rvmrc", "rvm use --create #{gemset}"

inside app_name do
  with_rvm 'rails generate bootstrap:install static'
  with_rvm 'rails generate controller static'
  with_rvm 'rails generate rspec:install'
  with_rvm 'rake db:migrate'
end

run 'rm app/views/layouts/application.html.erb'
new_file 'app/views/layouts/application.html.haml', File.read(File.expand_path('../application_layout.html.haml', __FILE__))

run 'rm public/index.html'
route "root to: 'static#index'"

new_file 'app/views/static/index.html.haml', <<-INDEX
%h1 Hello, #{app_name}!
INDEX

new_file 'app/assets/stylesheets/global.sass', <<-GLOBAL_SASS
.container-fluid
  margin-top: 50px
GLOBAL_SASS

git :init
git :add => '.'
git :commit => "-m 'Application generated by #{File.basename(__FILE__)}'"
